export const GET_DATA_PENDING = "GET_DATA_PENDING";
export const GET_DATA_SUCCESS = "GET_DATA_SUCCESS";
export const GET_LOCATION_SUCCESS = "GET_LOCATION_SUCCESS";
export const GET_SUGGESTIONS_SUCCESS = "GET_SUGGESTIONS_SUCCESS";
export const HIDE_SUGGESTIONS = "HIDE_SUGGESTIONS";
export const SHOW_SUGGESTIONS = "SHOW_SUGGESTIONS";
export const DEFAULT = "DEFAULT";
