export const AT = {
  GET_DATA_PENDING: "GET_DATA_PENDING",
  GET_DATA_SUCCESS: "GET_DATA_SUCCESS",
  GET_LOCATION_SUCCESS: "GET_LOCATION_SUCCESS",
  GET_SUGGESTIONS_PENDING: "GET_SUGGESTIONS_PENDING",
  GET_SUGGESTIONS_SUCCESS: "GET_SUGGESTIONS_SUCCESS",
  HIDE_SUGGESTIONS: "HIDE_SUGGESTIONS",
  SHOW_SUGGESTIONS: "SHOW_SUGGESTIONS",
  DEFAULT: "DEFAULT"
};
